format:
	clang-format -i -sort-includes *.cpp
	clang-format -i -sort-includes *.hpp

clean:
	rm -rf ../CMakeFiles
	rm -f ../CMakeCache.txt
	rm -f ../particle_simulation
	rm -f ../Makefile
	rm -f ../cmake_install.cmake

